### ISSUE TITLE
Unexpected token < import pdf from 'vue-pdf'; bundle

### ISSUE THREAD

**Issue by patrykKlimczak** [FranckFreiburger/vue-pdf#206] opened 2020-04-08 19:21 UTC
![image](https://user-images.githubusercontent.com/18028886/78823954-de263280-79dd-11ea-89db-7efdb438eaa6.png)

vue.config.js
```
chainWebpack: config => {
    config.optimization.splitChunks({
      cacheGroups: {
        vendors: {
          name: 'chunk-vendors',
          test: /[\\\/]node_modules[\\\\/]/,
          priority: -10,
          chunks: 'initial'
        },
        common: {
          name: 'chunk-common',
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          reuseExistingChunk: true
        }
      }
    })
  },
  configureWebpack: {
    output: {
      filename: 'js/[name].js',
      chunkFilename: 'js/[name].js',
    },
    plugins: [
      new WriteFilePlugin(),
      (process.env.NODE_ENV === "production" ?
        new BundleTracker({
          filename: 'webpack-stats-prod.json',
          publicPath: '/'
        }) :
        new BundleTracker({
          filename: 'webpack-stats.json',
          publicPath: 'http://localhost:8099/'
        })
      )
    ],
  }
```
![image](https://user-images.githubusercontent.com/18028886/78827589-9c988600-79e3-11ea-9c5a-a91dc9999e70.png)
![image](https://user-images.githubusercontent.com/18028886/78829562-da4ade00-79e6-11ea-8ef6-e716d92f6e24.png)

**Comment by patrykKlimczak** [comment] 2020-04-10 16:19
django port 8099
vue port 8082

On the vue app is good, but on django (port 8099) I have this error and pdf no load

**Comment by AlwaysSkylll** [comment] 2020-05-11 11:45
When I enter the page from other page, it's ok.
But when I refresh the page , there is the error " Unexpected token < "

![image](https://user-images.githubusercontent.com/13064486/81558222-e51ad900-93bf-11ea-8de2-8a3d1f1e6f52.png)

**Comment by songjishuai** [comment] 2020-05-27 01:33
I also encountered the same problem. Is there a solution?

**Comment by FranckFreiburger** [comment] 2020-06-08 20:08
Duplicate of #13

**Closed by FranckFreiburger** 2020-06-08 20:08 UTC
