### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < when work with electron-vue

### ISSUE THREAD

**Issue by K-Wen** [FranckFreiburger/vue-pdf#136] opened 2019-01-22 02:52 UTC
Hello!
I use [electron-vue](https://github.com/SimulatedGREG/electron-vue) with vue-pdf to show a pdf file in my desktop application. I do just as the basic usage in the README.md, but I got an error as below:

```
vm.js:74 Uncaught SyntaxError: Unexpected token <
    at new Script (vm.js:74)
    at createScript (vm.js:246)
    at Object.runInThisContext (vm.js:298)
    at Module._compile (internal/modules/cjs/loader.js:678)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
```

and it sames that the error was appear in vuePdfNoSss.vue file, before <style>.

```
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { **(HERE)**<style src="./annotationLayer.css"></style>
<script>

	import componentFactory from './componentFactory.js'

	if ( process.env.VUE_ENV !== 'server' ) {

		var pdfjsWrapper = require('./pdfjsWrapper.js').default;
		var PDFJS = require('pdfjs-dist/build/pdf.js');

		if ( typeof window !== 'undefined' && 'Worker' in window && navigator.appVersion.indexOf('MSIE 10') === -1 ) {

			var PdfjsWorker = require('worker-loader!pdfjs-dist/build/pdf.worker.js');
			PDFJS.GlobalWorkerOptions.workerPort = new PdfjsWorker();
		}

		var component = componentFactory(pdfjsWrapper(PDFJS));
	} else {

		var component = componentFactory({});
	}

	export default component;
</script>
}.call(this, exports, require, module, __filename, __dirname); });
```
It's very easy for this question to appear again, just use electron-vue to create a test proj and use vue-pdf. 

vue-pdf version: 4.0.5
vue.js version: 2.5.16
webpack version: 4.15.1
browser version: not in browser
electron version: 3.0.10
OS version: win 10 pro

**Comment by FranckFreiburger** [comment] 2019-01-25 08:03
It seems that vue-loader is not properly applied on this file

**Comment by FranckFreiburger** [comment] 2019-01-29 10:09
Duplicate of #13

**Closed by FranckFreiburger** 2019-01-29 10:09 UTC
