### ISSUE TITLE
Dependency not found: babel-runtime/regenerator

### ISSUE THREAD

**Issue by uboat46** [FranckFreiburger/vue-pdf#119] opened 2018-11-27 17:12 UTC
**USING**

 ```
"dependencies": {
    "animejs": "^2.2.0",
    "axios": "^0.18.0",
    "cheerio": "^1.0.0-rc.2",
    "firebase": "^5.5.8",
    "nuxt": "^2.2.0",
    "require": "^2.4.20",
    "vue-pdf": "^4.0.0",
    "vuelidate": "^0.7.4",
    "vuetify": "^1.3.6"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.7.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-html": "^4.0.6",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  }
```

**In Component.vue**

```
<template>
  <pdf :src="'~/assets/planes/actuaria.pdf'"></pdf>
</template>

<script>
import pdf from 'vue-pdf'

export default {
  components: {
    pdf
  }
}
</script>
```
**On Terminal**
```
This dependency was not found:

* babel-runtime/regenerator in ./node_modules/pdfjs-dist/lib/web/ui_utils.js

To install it, you can run: npm install --save babel-runtime/regenerator
```

**Comment by FranckFreiburger** [comment] 2018-11-28 10:08
does installing babel-runtime/regenerator solve the issue ?

**Comment by wangyalijas** [comment] 2018-12-06 06:00
I have the same problem. I want to know how to solve it.

**Comment by nassan** [comment] 2018-12-24 13:31
I solved it by installing `babel-runtime`, because I had an error installing `babel-runtime/regenerator` as npm does not see it as a package.

In other words, I ran `npm install --save babel-runtime`

**Comment by akaHeimdall** [comment] 2019-01-16 01:13
Just thought I'd add to what @nassan stated: installing `babel-runtime` solves the problem. Thanks.

**Comment by FranckFreiburger** [comment] 2019-01-29 09:02
Duplicate of #13

**Closed by FranckFreiburger** 2019-01-29 09:02 UTC

**Comment by jin-yong-yang** [comment] 2020-02-26 04:04
npm install --save @babel/runtime

**Comment by lemon-Boy** [comment] 2020-03-18 02:52
error is still exit after npm install --save babel-runtime

**Comment by stemount** [comment] 2022-02-19 05:12
For anyone still looking, `npm install --save @babel/runtime` is the way to go.
